# For the keys representing duration (i.e. the key ending with "-interval" or "-validity"), 
# the Go syntax is used. Valid units are "h", "m", "s", "ms", "us", "ns", e.g. "2h30m10s".

# Component configs
component-http-host-port: 0.0.0.0:8888
component-grpc-host-port: 0.0.0.0:5555

# Flaki ID generator
flaki: false
flaki-host-port: flaki:5555

# Keycloak configs
keycloak: false
keycloak-host-port: localhost:8080
keycloak-username: admin
keycloak-password: admin
keycloak-timeout: 5s
keycloak-client-creation-timeout: 40s

# Elasticsearch configs
elasticsearch: false
elasticsearch-host-port: elasticsearch-data:9200
elasticsearch-index-name: audit

# Redis
redis: false
redis-host-port: 
redis-password: 
redis-database: 0
redis-write-interval: 1s

# Cockroach configs
cockroach: false
cockroach-host-port: 
cockroach-username: 
cockroach-password: 
cockroach-database: 
cockroach-clean-interval: 1m

# Influx DB configs
influx: false
influx-host-port: 
influx-username: 
influx-password: 
influx-database: 
influx-precision: s
influx-retention-policy: ""
influx-write-consistency: ""
influx-write-interval: 1s

# Sentry configs
sentry: false
sentry-dsn: 

# Jaeger configs
jaeger: false
jaeger-sampler-type: const
jaeger-sampler-param: 1
jaeger-sampler-host-port: 
jaeger-reporter-logspan: false
jaeger-write-interval: 1s
jaeger-collector-healthcheck-host-port: 

# Debug routes
pprof-route-enabled: true

# Jobs
job: false
job-es-health-validity: 1m
job-flaki-health-validity: 1m
job-influx-health-validity: 1m
job-jaeger-health-validity: 1m
job-redis-health-validity: 1m
job-sentry-health-validity: 1m
job-keycloak-health-validity: 1m

# Rate limiting in requests/second.
rate-event: 1000
rate-user: 1000
