# For the keys representing duration (i.e. the key ending with "-interval" or "-validity"), 
# the Go syntax is used. Valid units are "h", "m", "s", "ms", "us", "ns", e.g. "2h30m10s".

# Component configs
component-http-host-port: 0.0.0.0:8888
component-grpc-host-port: 0.0.0.0:5555

# Flaki ID generator
flaki-host-port: flaki:5555

# Keycloak configs
keycloak-host-port: keycloak:80
keycloak-username: admin
keycloak-password: admin
keycloak-timeout: 5s

# Redis
redis-host-port: 
redis-password: 
redis-database: 0
redis-write-interval: 1s

# Cockroach configs
cockroach-host-port: localhost:26257
cockroach-username: cockroach
cockroach-password: cockroach
cockroach-config-database: config

# Influx DB configs
influx-host-port: 
influx-username: 
influx-password: 
influx-database: 
influx-precision: s
influx-retention-policy: ""
influx-write-consistency: ""
influx-write-interval: 1s

# Sentry configs
sentry-dsn: 

# Jaeger configs
jaeger-sampler-type: const
jaeger-sampler-param: 1
jaeger-sampler-host-port: 
jaeger-reporter-logspan: false
jaeger-write-interval: 1s
jaeger-collector-healthcheck-host-port: 

# Debug routes
pprof-route-enabled: true
